# docker-compose.yml
services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    restart: unless-stopped
    mem_limit: 500m             # redis 컨테이너에 할당되는 메모리: 500mb
    command:
      - "redis-server"
      - "--save"
      - "900"
      - "100"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
      - "--maxmemory"
      - "480mb"                 # redis의 메모리 상한선: 480mb (500mb가 되면 프로세스가 kill된다)
      - "--maxmemory-policy"    # 메모리 관리 정책 설정
      - "volatile-lru"          # 메모리 관리 정책: LRU
    ports:
      - "6379:6379"                        # 호스트 접속용 (원격 노출 불필요하면 제거)
    volumes:
      - redis-data:/data                   # RDB / AOF 영속화
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 5s
      retries: 5

volumes:
  redis-data: {}